Disable building chef-workstation-app globally

diff --git a/omnibus/package-scripts/cinc-workstation/postinst b/omnibus/package-scripts/cinc-workstation/postinst
--- a/omnibus/package-scripts/cinc-workstation/postinst
+++ b/omnibus/package-scripts/cinc-workstation/postinst
@@ -88,57 +88,57 @@ for link in $wrapper_links; do
   fi
 done
 
-if is_darwin; then
-  # the app launcher comes from the chef-workstation-app repo, here we are just using
-  # it to start the app as a service on MacOS systems, it will start at boot
-  app_launcher=chef_workstation_app_launcher
-
-  # Close the app if it is running.
-  if [ $(osascript -e 'application "Chef Workstation App" is running') = 'true' ]; then
-    echo "Closing Chef Workstation App..."
-    osascript -e 'quit app "Chef Workstation App"' > /dev/null 2>&1;
-  fi
-  # chef-workstation-app is configured to build Mac as a zip file instead
-  # of a directory. Otherwise, the mac pkgbuild command will find the Chef Workstation App
-  # within the larger Chef Workstation package, and will not include it in the Chef Workstation
-  # package directly.
-  echo "Moving Chef Workstation App to the Applications folder"
-  pushd "$INSTALLER_DIR/components/chef-workstation-app"
-  # https://github.com/electron-userland/electron-builder/issues/3779
-  # https://github.com/electron-userland/electron-builder/issues/4299#issuecomment-544997415
-  ditto -x -k -V chef-workstation-app-mac.zip ./
-  sudo rm -rf "/Applications/Chef Workstation App.app"
-  sudo mv "Chef Workstation App.app" /Applications/
-  mv "/Applications/Chef Workstation App.app/Contents/Resources/assets/scripts/$app_launcher" $INSTALLER_DIR/bin || error_exit "Cannot move $app_launcher to $INSTALLER_DIR/bin"
-  rm -f chef-workstation-app-mac.zip
-  popd
-
-  ln -sf $INSTALLER_DIR/bin/uninstall_chef_workstation $PREFIX/bin || error_exit "Cannot link uninstall_chef_workstation to $PREFIX/bin"
-
-  # Restart the app if it was running.
-  echo "Restarting Chef Workstation App..."
-  su "$USER" $INSTALLER_DIR/bin/$app_launcher load
-else # linux - postinst does not run for windows.
-  cwa_app_path="$INSTALLER_DIR/components/chef-workstation-app/chef-workstation-app"
-  ldd "$cwa_app_path" | grep "not found" >/dev/null 2>&1
-  # 0 rc means grep found 'not found' text - and we have missing deps.
-  if [ $? -eq 0 ]; then
-    echo ""
-    echo "To run the Cinc Workstation App, some additional dependencies must be installed."
-    echo "Using your platforms package manager to install the 'electron' package is "
-    echo "the easiest way to meet the dependency requirements."
-    echo ""
-    echo "You can then launch the App by running 'cinc-workstation-app'."
-    echo "The App will then be available in the system tray."
-  else
-    echo ""
-    echo "The Cinc Workstation App is available for you to try."
-    echo ""
-    echo "Launch the App by running 'cinc-workstation-app'."
-    echo "The App will then be available in the system tray."
-  fi
-  ln -sf $cwa_app_path $PREFIX/bin
-fi
+# if is_darwin; then
+#   # the app launcher comes from the chef-workstation-app repo, here we are just using
+#   # it to start the app as a service on MacOS systems, it will start at boot
+#   app_launcher=chef_workstation_app_launcher
+#
+#   # Close the app if it is running.
+#   if [ $(osascript -e 'application "Chef Workstation App" is running') = 'true' ]; then
+#     echo "Closing Chef Workstation App..."
+#     osascript -e 'quit app "Chef Workstation App"' > /dev/null 2>&1;
+#   fi
+#   # chef-workstation-app is configured to build Mac as a zip file instead
+#   # of a directory. Otherwise, the mac pkgbuild command will find the Chef Workstation App
+#   # within the larger Chef Workstation package, and will not include it in the Chef Workstation
+#   # package directly.
+#   echo "Moving Chef Workstation App to the Applications folder"
+#   pushd "$INSTALLER_DIR/components/chef-workstation-app"
+#   # https://github.com/electron-userland/electron-builder/issues/3779
+#   # https://github.com/electron-userland/electron-builder/issues/4299#issuecomment-544997415
+#   ditto -x -k -V chef-workstation-app-mac.zip ./
+#   sudo rm -rf "/Applications/Chef Workstation App.app"
+#   sudo mv "Chef Workstation App.app" /Applications/
+#   mv "/Applications/Chef Workstation App.app/Contents/Resources/assets/scripts/$app_launcher" $INSTALLER_DIR/bin || error_exit "Cannot move $app_launcher to $INSTALLER_DIR/bin"
+#   rm -f chef-workstation-app-mac.zip
+#   popd
+#
+#   ln -sf $INSTALLER_DIR/bin/uninstall_chef_workstation $PREFIX/bin || error_exit "Cannot link uninstall_chef_workstation to $PREFIX/bin"
+#
+#   # Restart the app if it was running.
+#   echo "Restarting Chef Workstation App..."
+#   su "$USER" $INSTALLER_DIR/bin/$app_launcher load
+# else # linux - postinst does not run for windows.
+#   cwa_app_path="$INSTALLER_DIR/components/chef-workstation-app/chef-workstation-app"
+#   ldd "$cwa_app_path" | grep "not found" >/dev/null 2>&1
+#   # 0 rc means grep found 'not found' text - and we have missing deps.
+#   if [ $? -eq 0 ]; then
+#     echo ""
+#     echo "To run the Cinc Workstation App, some additional dependencies must be installed."
+#     echo "Using your platforms package manager to install the 'electron' package is "
+#     echo "the easiest way to meet the dependency requirements."
+#     echo ""
+#     echo "You can then launch the App by running 'cinc-workstation-app'."
+#     echo "The App will then be available in the system tray."
+#   else
+#     echo ""
+#     echo "The Cinc Workstation App is available for you to try."
+#     echo ""
+#     echo "Launch the App by running 'cinc-workstation-app'."
+#     echo "The App will then be available in the system tray."
+#   fi
+#   ln -sf $cwa_app_path $PREFIX/bin
+# fi
 
 echo ""
 echo "Thank you for installing Cinc Workstation!"
