Cinc stable patches
- Switch to using cinc patched gems from packagecloud to work around issues
  using path: with the Gemfile.
- Pull build_version from the VERSION file since we aren't tagging our own
  releases
- Properly update Gemfile.lock with more Cinc patched gems
- Fix package-scripts
- Update windows source.wxs file
- Use a relative path

diff --git a/omnibus/package-scripts/cinc-workstation/postinst b/omnibus/package-scripts/cinc-workstation/postinst
--- a/omnibus/package-scripts/cinc-workstation/postinst
+++ b/omnibus/package-scripts/cinc-workstation/postinst
@@ -5,7 +5,7 @@
 #
 
 PROGNAME=`basename $0`
-INSTALLER_DIR=/opt/chef-workstation
+INSTALLER_DIR=/opt/cinc-workstation
 
 error_exit()
 {
@@ -25,10 +25,19 @@ else
     PREFIX="/usr"
 fi
 
-binaries="chef-run berks chef chef-cli chef-analyze chef-apply chef-shell chef-solo chef-vault cookstyle delivery foodcritic inspec kitchen knife ohai push-apply pushy-client pushy-service-manager chef-client"
+binaries="chef-run berks chef chef-cli chef-analyze cinc-apply cinc-shell cinc-solo chef-vault cookstyle delivery foodcritic cinc-auditor kitchen knife ohai push-apply pushy-client pushy-service-manager cinc-client"
 
 for binary in $binaries; do
   ln -sf "$INSTALLER_DIR/bin/$binary" $PREFIX/bin || error_exit "Cannot link $binary to $PREFIX/bin"
+done
+
+wrapper_links="chef-apply chef-client chef-shell chef-solo inspec"
+link_target="cinc-wrapper"
+for link in $wrapper_links; do
+  if [ ! -e $PREFIX/bin/$link ]; then
+    echo "Symlinking $link command to cinc-wrapper for compatibility..."
+    ln -sf $INSTALLER_DIR/bin/$link_target $PREFIX/bin/$link || error_exit "Cannot link $link_target to $PREFIX/bin/$link"
+  fi
 done
 
 if is_darwin; then
@@ -67,24 +76,24 @@ else # linux - postinst does not run for windows.
   # 0 rc means grep found 'not found' text - and we have missing deps.
   if [ $? -eq 0 ]; then
     echo ""
-    echo "To run the Chef Workstation App, use your"
+    echo "To run the Cinc Workstation App, use your"
     echo "platform's package manager to install these dependencies:"
     echo ""
     ldd "$cwa_app_path" | grep "not found" 2>&1
-    echo "You can then launch the App by running 'chef-workstation-app'."
+    echo "You can then launch the App by running 'cinc-workstation-app'."
     echo "The App will then be available in the system tray."
   else
     echo ""
-    echo "The Chef Workstation App is available for you to try."
+    echo "The Cinc Workstation App is available for you to try."
     echo ""
-    echo "Launch the App by running 'chef-workstation-app'."
+    echo "Launch the App by running 'cinc-workstation-app'."
     echo "The App will then be available in the system tray."
   fi
   ln -sf $cwa_app_path $PREFIX/bin
 fi
 
 echo ""
-echo "Thank you for installing Chef Workstation!"
-echo "You can find some tips on getting started at https://chef.sh/"
+echo "Thank you for installing Cinc Workstation!"
+echo "You can find some tips on getting started at https://cinc.sh/"
 echo ""
 exit 0
